name: Refresh-Rclone-Token

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Check Drive Capacity
        run: "rclone about remote:"

      - name: Delete old Workflows
        uses: ophub/delete-releases-workflows@main
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          delete_releases: true
          releases_keep_latest: 0
          delete_tags: true
          delete_workflows: true
          workflows_keep_day: 0
          workflows_keep_keyword: "Build"